# Discussion

## Strengths

The high R-square values and residuals which are quite normalised presents a good case of how HDB resale flat prices can be modelled. For cluster analysis, it opens up the opportunity to examine street level trends using the chosen numerical summaries.

## Weaknesses

For regression, parks and primary schools did not have a significant effect on price, that was not as what I have expected. It could have other variables or reasons to better estimate the coefficients. The study consider 1km as the cut-off distance, which can be amended to 0.5, 1 and 1.5km for analysis. For clustering, the choice of street level may not be a good perspective. 

## Possible Further Studies

The study focus on local level price dynamics of HDB prices by choosing an estate in the East and Northwest of Singapore. Tampines as one of the five other emerging hubs (Woodlands, Changi, Jurong Lake, Punggol Digital) to decentralise Singapore is a good motivation to study the trend. An extended study can be done to explore the all the stations on the Downtown Line. This could be compared to other opening of MRT is the recent decades such as the Circle Line. Thomson-East Coast Line could have similar trajectory based on the variables provided by DataGov. 

Bukit Panjang has an LRT station connected from Choa Chu Kang to Bukit Panjang which was not considered in this study. The bus system acts compliments the MRT in other estates which hig frequency that may not be an important. A comparsion with Punggol and Sengkang would be appropriate since they have an existing LRT line.

Private properties are not considered and the impact of new MRT station affects the real estate values for speculative and investment returns.

K Means on Bukit Panjang can be done to find patterns. Also, other variables can be included and then dimensional reduction can be done to sieve out the critical variables that affect resale prices with the highest impact.
